scrape_configs:
  - job_name: envoy
    scrape_interval: 1s
    metrics_path: /stats/prometheus
    static_configs:
      - targets: ["127.0.0.1:8001"]
  - job_name: exp
    scrape_interval: 1s
    metrics_path: /metrics
    static_configs:
      - targets: ["127.0.0.1:8083"]
